### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by isghe** [rgb-org/spec#15]
Let's follow https://semver.org rules

**Comment by dr-orlovsky** [comment]
I'm afraid we can't directly follow the semver rules since contract and proofs structure is more rigid and can't allow some "patches". We will use semver for versioning the software implementing the spec; however for the spec itself I think we should take some core ideas from the semver and stick to major-minor versioning dichotomy as I proposed in this commit: https://github.com/rgb-org/spec/commit/5c12ef60ce9c1f46fc1abd2e2a49c2c84dc2b047
